const flatsList = [
    {
        img: '/img/four-01-card.jpg',
        scheme: '/img/four-01-scheme.png',
        addition: 'Доступно ещё 15 планировок!',
        title: '1 комнатная квартира',
        text: 'Современная квартира с видом на центр города через панорамные окна. Эффективная планировка. Большая кухня-гостиная для вечеринок с друзьями.',
        price: '2,65 млн.Р',
        monthly: '12 000 Р/мес',
        square: '35 кв.м',
        section: '6',
        floor: '12',
    },
    {
        img: '/img/four-02-card.jpg',
        scheme: '/img/four-01-scheme.png',
        addition: 'Lorem ipsum dolor sit amet',
        title: 'Lorem ipsum dolor',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro nobis nihil accusamus vel quis recusandae.',
        price: '2,65 млн.Р',
        monthly: '12 000 Р/мес',
        square: '35 кв.м',
        section: '6',
        floor: '12',
    },
    {
        img: '/img/four-01-card.jpg',
        scheme: '/img/four-01-scheme.png',
        addition: 'Lorem ipsum dolor sit amet',
        title: 'Lorem ipsum dolor',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro nobis nihil accusamus vel quis recusandae.',
        price: '2,65 млн.Р',
        monthly: '12 000 Р/мес',
        square: '35 кв.м',
        section: '6',
        floor: '12',
    },
    {
        img: '/img/four-02-card.jpg',
        scheme: '/img/four-01-scheme.png',
        addition: 'Lorem ipsum dolor sit amet',
        title: 'Lorem ipsum dolor',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro nobis nihil accusamus vel quis recusandae.',
        price: '2,65 млн.Р',
        monthly: '12 000 Р/мес',
        square: '35 кв.м',
        section: '6',
        floor: '12',
    },
    {
        img: '/img/four-01-card.jpg',
        scheme: '/img/four-01-scheme.png',
        addition: 'Lorem ipsum dolor sit amet',
        title: 'Lorem ipsum dolor',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro nobis nihil accusamus vel quis recusandae.',
        price: '2,65 млн.Р',
        monthly: '12 000 Р/мес',
        square: '35 кв.м',
        section: '6',
        floor: '12',
    },

]

export default flatsList;